version = "2.5.18"

[source]
url = "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.5.18.tar.bz2"
sha256 = "0dbd64e0322fe1a4813360d46539d5f8daf4a8fa235cf5fce464e8b0214a7e4f"

[signature]
type = "gpg"
url = "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.5.18.tar.bz2.sig"
expected_keys = [
    "6DAA6E64A76D2840571B4902528897B826403ADA",
    "AC8E115BF73E2D8D47FA9908E98E9B2D19C6C8BD"
]

[build]
system = "autotools"
configure_args = ["--enable-shared"]
